### ISSUE TITLE
SyntaxError: "[object Object]" is not valid JSON 

### ISSUE THREAD

**Issue by saradasilva** [jowavp/sap-cf-destconn#10]
Error at JSON.parse (<anonymous>)
    at logAxiosError (/node_modules/sap-cf-destconn/dist/destination.js:285:28)
    at createToken (/node_modules/sap-cf-destconn/dist/destination.js:199:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async readDestination (/node_modules/sap-cf-destconn/dist/destination.js:35:26)

I'm executing my application that is not multitentant and destinations are at instance level. This library worked fine until now and I think the issue is in this line:
https://github.com/jowavp/sap-cf-destconn/blob/6919020b903f5f88cc85b8a279479b5259ebe480/src/destination.ts#L299

it should be destination.uaa

Because I'm receiving this structure in fetchToken:
![image](https://user-images.githubusercontent.com/64361857/233847398-0bcb1365-947b-42f5-933a-e4c8fb1e4459.png)

My code gets ds.url

![image](https://user-images.githubusercontent.com/64361857/233847495-48484ec4-c174-4b4c-95f3-c649475a38dc.png)

But this is undefined, because it should be ds.uaa.url

![image](https://user-images.githubusercontent.com/64361857/233847535-6f729694-d5b3-4045-bd66-ebfc8c6bbe58.png)

In consequence, tokenBaseUrl is undefined and it cannot fetch token to read destinations

**Comment by saradasilva** [comment]
Hello team.

I found the issue, when you execute readDestination deployed it's ok because build artifact uses default-env, but now with version cds 6 from CAP, I'm using cds bind --to <instanceName>:<key> to bind destination instance, so it returns destination.uaa
